[build]
  base = "."
  publish = "client/dist"
  command = "cd server && npm install && cd ../client && npm install --include=dev && npm run build"

[functions]
  node_bundler = "esbuild"
  directory = "server/netlify/functions"
  external_node_modules = ["*"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
