[build]
  base = "."
  publish = "client/dist"
  command = "cd server && npm install && cd ../client && npm install --include=dev && npm run build"

[functions]
  node_bundler = "esbuild"
  directory = "server/netlify/functions"
  external_node_modules = ["pg", "pg-hstore"]
  included_files = ["server/node_modules/pg/**", "server/node_modules/pg-hstore/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
